import fs from "fs/promises";
import pdfParse from "pdf-parse/lib/pdf-parse.js";
import Medicine from "../models/Medicine.js";
import Prescription from "../models/Prescription.js";
import { AppError } from "../middleware/errorHandler.js";
import * as gemini from "./gemini.service.js";
import * as groq from "./groq.service.js";

/**
 * ============================================================================
 * AI Gateway
 *
 * The single entry point for every AI-related operation in the app.
 * Controllers must NEVER import gemini.service.js or groq.service.js
 * directly — they always go through the methods exposed here. This is
 * what enforces the model split described in the AI architecture:
 *
 *   Gemini  -> ai/gemini.service.js -> OCR, extraction, structured JSON
 *   Groq    -> ai/groq.service.js   -> summaries, explanations, chat
 *
 * AI FLOW
 * User uploads prescription
 *   -> analyzePrescription()      [Gemini: image/PDF -> structured JSON]
 *   -> (controller stores JSON in MongoDB)
 *   -> generateSummary()          [Groq: structured JSON -> plain summary]
 *   -> medicineExplanation()      [Groq: per-medicine explanation]
 *   -> checkInteractions()        [Groq: drug interaction explanation]
 *   -> (controller returns results for the dashboard)
 * ============================================================================
 */

export const REVIEW_CONFIDENCE_THRESHOLD = gemini.REVIEW_CONFIDENCE_THRESHOLD;

/**
 * Extracts structured prescription data from an uploaded file using
 * Gemini. Routes images straight to Gemini Vision; for PDFs, pulls the
 * embedded text layer first (pdf-parse — not an AI call) and sends that
 * text to Gemini, since Gemini needs either image bytes or text, not a
 * raw PDF. A PDF with no embedded text layer is almost always a scanned
 * image saved as PDF, which needs a photo re-upload instead.
 *
 * @param {string} filePath - absolute path to the uploaded file on disk
 * @param {"image"|"pdf"} fileType
 * @param {string} mimeType - the file's original MIME type (used for images)
 * @returns {Promise<{ocrText: string, medicines: Array, doctorNotes: string, confidence: number}>}
 */
export async function analyzePrescription(filePath, fileType, mimeType) {
  try {
    if (fileType === "pdf") {
      const buffer = await fs.readFile(filePath);
      const { text } = await pdfParse(buffer);
      const embeddedText = (text || "").trim();

      if (!embeddedText || embeddedText.length < 5) {
        throw new AppError(
          "This PDF has no readable text layer, which usually means it's a scanned image saved as a PDF. Please upload it as a photo (JPG, PNG, or WEBP) instead.",
          422
        );
      }

      const result = await gemini.extractFromText(embeddedText);
      if (!result.ocrText) result.ocrText = embeddedText;
      return result;
    }

    return await gemini.extractFromImage(filePath, mimeType);
  } catch (err) {
    if (err instanceof AppError) throw err;
    console.error(`[AI Gateway] Prescription extraction failed: ${err.message}`);
    throw new AppError(
      "Failed to read this prescription with AI. Please try again with a clearer photo.",
      502
    );
  }
}

/**
 * "Prescription Summary" — one short plain-language paragraph for the
 * whole prescription, generated by Groq from the already-structured
 * medicine list. Not persisted (no schema change) — returned directly
 * in the API response for the dashboard to display.
 *
 * @param {{medicines: Array, doctorNotes?: string}} structuredJson
 */
export async function generateSummary(structuredJson, language) {
  return groq.generateSummary(structuredJson, language);
}

/**
 * "Medicine Explanation" for a single medicine — summary, common uses,
 * side effects, precautions — generated by Groq.
 *
 * @param {string} [language] - "en" | "hi" | "gu", the user's dashboard language preference
 */
export async function medicineExplanation({ name, dosage, frequency, instructions }, language) {
  return groq.explainMedicine({ name, dosage, frequency, instructions }, language);
}

/**
 * "Drug Interaction Explanation" across a list of medicine names,
 * generated by Groq.
 *
 * @param {string} [language] - "en" | "hi" | "gu", the user's dashboard language preference
 */
export async function checkInteractions(medicineNames, language) {
  return groq.checkInteractions(medicineNames, language);
}

// How many prior turns (user+assistant pairs) to send as chat history.
// Keeps token usage bounded on long threads without losing recent context.
const MAX_CHAT_HISTORY_MESSAGES = 16;

/**
 * Builds a compact, plain-text summary of the user's own confirmed
 * medicines and recent prescriptions so the chatbot can answer
 * questions grounded in their actual data instead of generic
 * information only.
 */
async function buildUserContext(userId) {
  const [medicines, prescriptions] = await Promise.all([
    Medicine.find({ user: userId, needsReview: false })
      .select("name dosage frequency instructions")
      .sort({ createdAt: -1 })
      .limit(30),
    Prescription.find({ user: userId })
      .select("doctorName prescriptionDate status createdAt")
      .sort({ createdAt: -1 })
      .limit(5),
  ]);

  if (medicines.length === 0 && prescriptions.length === 0) {
    return "This user hasn't uploaded any prescriptions or confirmed any medicines yet.";
  }

  const medicineLines = medicines.length
    ? medicines
        .map(
          (m) =>
            `- ${m.name}${m.dosage ? ` (${m.dosage})` : ""}${
              m.frequency ? `, ${m.frequency}` : ""
            }${m.instructions ? `, ${m.instructions}` : ""}`
        )
        .join("\n")
    : "None confirmed yet.";

  const prescriptionLines = prescriptions.length
    ? prescriptions
        .map((p) => {
          const date = p.prescriptionDate || p.createdAt;
          const dateStr = date ? new Date(date).toLocaleDateString() : "unknown date";
          return `- ${p.doctorName ? `From ${p.doctorName}, ` : ""}${dateStr} (${p.status})`;
        })
        .join("\n")
    : "None yet.";

  return `Current confirmed medicines:\n${medicineLines}\n\nRecent prescriptions:\n${prescriptionLines}`;
}

/**
 * "AI Chatbot" / "General Medicine Questions" / "General Health
 * Guidance" — generated by Groq, grounded in the user's own medicine
 * context.
 *
 * @param {Array<{role: "user"|"assistant", content: string}>} priorMessages - excludes the new message
 * @param {string} newUserMessage
 * @param {string} userId
 * @param {string} [language] - "en" | "hi" | "gu", the user's dashboard language preference
 */
export async function chat(priorMessages, newUserMessage, userId, language) {
  const context = await buildUserContext(userId);
  const history = priorMessages.slice(-MAX_CHAT_HISTORY_MESSAGES);

  const reply = await groq.generateChatReply({ context, history, newMessage: newUserMessage, language });
  if (!reply) {
    throw new AppError("The assistant didn't return a response. Please try again.", 502);
  }
  return reply;
}

/**
 * "AI Lab Report Analyzer" — extraction step. Same routing logic as
 * analyzePrescription (image -> Gemini Vision, PDF -> embedded text ->
 * Gemini text prompt), just pointed at the lab-report prompt/normalizer
 * instead of the prescription one.
 *
 * @param {string} filePath
 * @param {"image"|"pdf"} fileType
 * @param {string} mimeType
 * @returns {Promise<{labName: string, reportDate: string, results: Array, uncertainNote: string, confidence: number}>}
 */
export async function analyzeLabReport(filePath, fileType, mimeType) {
  try {
    if (fileType === "pdf") {
      const buffer = await fs.readFile(filePath);
      const { text } = await pdfParse(buffer);
      const embeddedText = (text || "").trim();

      if (!embeddedText || embeddedText.length < 5) {
        throw new AppError(
          "This PDF has no readable text layer, which usually means it's a scanned image saved as a PDF. Please upload it as a photo (JPG, PNG, or WEBP) instead.",
          422
        );
      }

      return await gemini.extractLabReportFromText(embeddedText);
    }

    return await gemini.extractLabReportFromImage(filePath, mimeType);
  } catch (err) {
    if (err instanceof AppError) throw err;
    console.error(`[AI Gateway] Lab report extraction failed: ${err.message}`);
    throw new AppError(
      "Failed to read this lab report with AI. Please try again with a clearer file.",
      502
    );
  }
}

/**
 * "Lab Report Analysis" — explanation step. Takes Gemini's already-
 * extracted structured results and asks Groq for a plain-language
 * overall summary plus per-result explanations.
 */
export async function explainLabReport(structuredJson, language) {
  return groq.explainLabReport(structuredJson, language);
}

/**
 * "AI Personalized Medical Diet Guide" — takes the user's supplied
 * health context and (optionally) a lab report's already-extracted
 * results and asks Groq for structured, educational dietary guidance.
 * No document/image understanding is needed here (the lab report, if
 * any, was already analyzed by Gemini in a prior step and its
 * structured results are simply passed through), so this goes straight
 * to Groq rather than through Gemini first.
 *
 * @param {{healthContext: object, labReport?: {labName?: string, reportDate?: string, results: Array}, language?: string}} params
 */
export async function generateDietGuide({ healthContext, labReport, language }) {
  try {
    return await groq.generateDietGuide({ healthContext, labReport, language });
  } catch (err) {
    if (err instanceof AppError) throw err;
    console.error(`[AI Gateway] Diet guide generation failed: ${err.message}`);
    throw new AppError(
      "Failed to generate your diet guide with AI. Please try again.",
      502
    );
  }
}

export default {
  REVIEW_CONFIDENCE_THRESHOLD,
  analyzePrescription,
  generateSummary,
  medicineExplanation,
  checkInteractions,
  chat,
  analyzeLabReport,
  explainLabReport,
  generateDietGuide,
};
